# Cross-platform build pipeline

name: $(Build.SourceVersion)
jobs:
- job: Ubuntu1604
  displayName: "Linux - Ubuntu 16.04"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: .ci/esy-build-steps.yml

- job: Ubuntu1804
  displayName: "Linux - Ubuntu 18.04"
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: .ci/esy-build-steps.yml

- job: MacOS14
  displayName: "MacOS Mojave"
  pool:
    vmImage: 'macOS 10.14'
  steps:
  - template: .ci/esy-build-steps.yml

- job: MacOS15
  displayName: "MacOS Catalina"
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: .ci/esy-build-steps.yml

- job: Windows2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/esy-build-steps.yml

- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: .ci/esy-build-steps.yml
